# Generated by Django 3.0.5 on 2020-04-08 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wafting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='M', max_length=1)),
                ('emotion', models.CharField(choices=[('H', 'Happy'), ('S', 'Sad'), ('H', 'Humorous'), ('A', 'Angry')], default='H', max_length=1)),
                ('scent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Scent')),
            ],
        ),
    ]
