# Generated by Django 3.0.5 on 2020-04-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_wafting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wafting',
            name='date',
            field=models.DateField(verbose_name='Smelling Date'),
        ),
    ]
