# Generated by Django 3.0.5 on 2020-04-08 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200408_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wafting',
            name='time',
        ),
    ]
