# Generated by Django 3.0.5 on 2020-04-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_wafting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wafting',
            name='emotion',
            field=models.CharField(choices=[('H', 'Happy'), ('S', 'Sad'), ('L', 'Laughter'), ('A', 'Angry')], default='H', max_length=1),
        ),
    ]
