# Generated by Django 3.0.5 on 2020-04-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200408_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wafting',
            options={'ordering': ['-date']},
        ),
    ]
